import type { PublicComment } from "./types";

export const COMMUNITY_COMMENTS: PublicComment[] = [
  {
    id: "c-summit-1",
    articleId: "summit",
    author: "Rafael Lima",
    titlePrefix: "Dr.",
    specialty: "Cardiologia",
    text: "HR 0,62 puxado por descompensação, não por morte CV (IC cruza 1). Em HFpEF com obesidade já em SGLT2, titula tirzepatida. Fora desse fenótipo, o SUMMIT não autoriza.",
    rating: 5,
    createdAt: "2026-09-08T11:20:00.000Z",
  },
  {
    id: "c-summit-2",
    articleId: "summit",
    author: "Helena Costa",
    titlePrefix: "Dra.",
    specialty: "Cardiologia",
    text: "KCCQ +6,9 é clinicamente sentível. Amostra curta para mortalidade. Financiamento Lilly no rodapé — leio o composto, não o press-release.",
    rating: 4,
    createdAt: "2026-09-09T08:10:00.000Z",
  },
  {
    id: "c-surmount-1",
    articleId: "surmount",
    author: "Paulo Mendes",
    titlePrefix: "Dr.",
    specialty: "Endocrinologia",
    text: "Aberto, balança objetiva. 6,5 pontos percentuais importam. Não troco quem está bem em semaglutida 2,4 só por pódio de peso — comorbidade guia a classe.",
    rating: 4,
    createdAt: "2026-09-07T14:00:00.000Z",
  },
  {
    id: "c-select-1",
    articleId: "select",
    author: "Marina Alves",
    titlePrefix: "Dra.",
    specialty: "Cardiologia",
    text: "MACE 20% em prevenção secundária sem DM2. A curva separa cedo demais para ser só peso. Inércia de ‘mais um ano de dieta’ ficou difícil de defender.",
    rating: 5,
    createdAt: "2026-09-06T09:40:00.000Z",
  },
  {
    id: "c-flow-1",
    articleId: "flow",
    author: "Igor Nunes",
    titlePrefix: "Dr.",
    specialty: "Nefrologia",
    text: "Dose 1 mg, muitos já em SGLT2. O GLP-1 entra na tríade, não no lugar do SGLT2. DRC sem diabetes continua território do empa/dapa.",
    rating: 5,
    createdAt: "2026-09-05T16:12:00.000Z",
  },
  {
    id: "c-empa-1",
    articleId: "empa-kidney",
    author: "Igor Nunes",
    titlePrefix: "Dr.",
    specialty: "Nefrologia",
    text: "O paper que eu mostro quando perguntam ‘e se não for diabético?’. SGLT2 primeiro; o resto é adicional.",
    rating: 5,
    createdAt: "2026-09-04T10:00:00.000Z",
  },
  {
    id: "c-esc-1",
    articleId: "esc-af",
    author: "Camila Rocha",
    titlePrefix: "Dra.",
    specialty: "Cardiologia",
    text: "CHA₂DS₂-VA sem o sexo isolado. AF-CARE é mnemônico útil. Ablação precoce esbarra em fila — o texto da ESC não cria vaga no eletrofisio.",
    rating: 4,
    createdAt: "2026-09-03T12:30:00.000Z",
  },
  {
    id: "c-aspree-1",
    articleId: "aspree",
    author: "Lúcia Prado",
    titlePrefix: "Dra.",
    specialty: "Geriatria",
    text: "Desprescrição de AAS em primária no idoso deveria ser checklist de consulta. Secundária não se discute aqui.",
    rating: 5,
    createdAt: "2026-09-02T18:00:00.000Z",
  },
  {
    id: "c-danger-1",
    articleId: "danger-shock",
    author: "Bruno Teixeira",
    titlePrefix: "Dr.",
    specialty: "Medicina Intensiva",
    text: "HR 0,74 com IC tocando 0,99 e custo hemorrágico. Dado de centro que faz volume. Não improvisa Impella em hospital sem vascular de retaguarda.",
    rating: 4,
    createdAt: "2026-09-01T07:15:00.000Z",
  },
  {
    id: "c-orbita-1",
    articleId: "orbita2",
    author: "Rafael Lima",
    titlePrefix: "Dr.",
    specialty: "Cardiologia",
    text: "Sintoma sim, seguro de vida não. ISCHEMIA continua no mural dos desfechos duros. ORBITA-2 limpa o efeito placebo do cateterismo.",
    rating: 5,
    createdAt: "2026-08-30T11:45:00.000Z",
  },
  {
    id: "c-mash-1",
    articleId: "mash",
    author: "Sofia Martins",
    titlePrefix: "Dra.",
    specialty: "Hepatologia",
    text: "Fase 2, dose diária ≠ caneta de 2,4. Histologia boa, desfecho de cirrose ainda não. Confiança média está correta no resumo.",
    rating: 3,
    createdAt: "2026-08-28T13:20:00.000Z",
  },
  {
    id: "c-sprint-1",
    articleId: "sprint",
    author: "André Dias",
    titlePrefix: "Dr.",
    specialty: "Medicina Interna",
    text: "Copiar 120 sem copiar o método de medida é o erro clássico. No frágil, outro alvo. No autônomo de alto risco, 140 é folga.",
    rating: 5,
    createdAt: "2026-08-27T09:00:00.000Z",
  },
  {
    id: "c-balance-1",
    articleId: "balance",
    author: "Renata Pires",
    titlePrefix: "Dra.",
    specialty: "Infectologia",
    text: "7 dias em foco controlado. S. aureus, endocardite, abscesso residual: ignore o título. Stewardship com desfecho de morte, não só DDD.",
    rating: 5,
    createdAt: "2026-08-26T15:40:00.000Z",
  },
  {
    id: "c-clear-1",
    articleId: "clear",
    author: "Helena Costa",
    titlePrefix: "Dra.",
    specialty: "Cardiologia",
    text: "Antes de rotular intolerância, tenta outra estatina. Bempedoico é a peça oral que faltava; gota no radar. Não substitui PCSK9 se o alvo é 40.",
    rating: 4,
    createdAt: "2026-08-25T10:05:00.000Z",
  },
  {
    id: "c-rsv-1",
    articleId: "rsv",
    author: "Lúcia Prado",
    titlePrefix: "Dra.",
    specialty: "Geriatria",
    text: "Ofereço na temporada junto com influenza. Não substitui pneumococo. RSV do idoso deixou de ser nota de rodapé de pediatria.",
    rating: 4,
    createdAt: "2026-08-24T08:50:00.000Z",
  },
];

export function communityFor(articleId: string): PublicComment[] {
  return COMMUNITY_COMMENTS.filter((c) => c.articleId === articleId);
}
