/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppArtigosRouteImport } from './routes/_app/artigos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppMascoteRouteImport } from './routes/_app/mascote'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as ArtigoIdRouteImport } from './routes/artigo.$id'
import { Route as EdicaoIdRouteImport } from './routes/edicao.$id'
import { Route as LerIdRouteImport } from './routes/ler.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppArtigosRoute = AppArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppMascoteRoute = AppMascoteRouteImport.update({
  id: '/mascote',
  path: '/mascote',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const ArtigoIdRoute = ArtigoIdRouteImport.update({
  id: '/artigo/$id',
  path: '/artigo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicaoIdRoute = EdicaoIdRouteImport.update({
  id: '/edicao/$id',
  path: '/edicao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LerIdRoute = LerIdRouteImport.update({
  id: '/ler/$id',
  path: '/ler/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamento': typeof PagamentoRoute
  '/planos': typeof PlanosRoute
  '/artigos': typeof AppArtigosRoute
  '/dashboard': typeof AppDashboardRoute
  '/insights': typeof AppInsightsRoute
  '/mascote': typeof AppMascoteRoute
  '/perfil': typeof AppPerfilRoute
  '/artigo/$id': typeof ArtigoIdRoute
  '/edicao/$id': typeof EdicaoIdRoute
  '/ler/$id': typeof LerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamento': typeof PagamentoRoute
  '/planos': typeof PlanosRoute
  '/artigos': typeof AppArtigosRoute
  '/dashboard': typeof AppDashboardRoute
  '/insights': typeof AppInsightsRoute
  '/mascote': typeof AppMascoteRoute
  '/perfil': typeof AppPerfilRoute
  '/artigo/$id': typeof ArtigoIdRoute
  '/edicao/$id': typeof EdicaoIdRoute
  '/ler/$id': typeof LerIdRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamento': typeof PagamentoRoute
  '/planos': typeof PlanosRoute
  '/_app/artigos': typeof AppArtigosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/mascote': typeof AppMascoteRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/artigo/$id': typeof ArtigoIdRoute
  '/edicao/$id': typeof EdicaoIdRoute
  '/ler/$id': typeof LerIdRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/login'
    | '/onboarding'
    | '/pagamento'
    | '/planos'
    | '/artigos'
    | '/dashboard'
    | '/insights'
    | '/mascote'
    | '/perfil'
    | '/artigo/$id'
    | '/edicao/$id'
    | '/ler/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/config'
    | '/login'
    | '/onboarding'
    | '/pagamento'
    | '/planos'
    | '/artigos'
    | '/dashboard'
    | '/insights'
    | '/mascote'
    | '/perfil'
    | '/artigo/$id'
    | '/edicao/$id'
    | '/ler/$id'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/config'
    | '/login'
    | '/onboarding'
    | '/pagamento'
    | '/planos'
    | '/_app/artigos'
    | '/_app/dashboard'
    | '/_app/insights'
    | '/_app/mascote'
    | '/_app/perfil'
    | '/artigo/$id'
    | '/edicao/$id'
    | '/ler/$id'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ConfigRoute: typeof ConfigRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PagamentoRoute: typeof PagamentoRoute
  PlanosRoute: typeof PlanosRoute
  ArtigoIdRoute: typeof ArtigoIdRoute
  EdicaoIdRoute: typeof EdicaoIdRoute
  LerIdRoute: typeof LerIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artigos': {
      id: '/_app/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof AppArtigosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mascote': {
      id: '/_app/mascote'
      path: '/mascote'
      fullPath: '/mascote'
      preLoaderRoute: typeof AppMascoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/artigo/$id': {
      id: '/artigo/$id'
      path: '/artigo/$id'
      fullPath: '/artigo/$id'
      preLoaderRoute: typeof ArtigoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicao/$id': {
      id: '/edicao/$id'
      path: '/edicao/$id'
      fullPath: '/edicao/$id'
      preLoaderRoute: typeof EdicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ler/$id': {
      id: '/ler/$id'
      path: '/ler/$id'
      fullPath: '/ler/$id'
      preLoaderRoute: typeof LerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppArtigosRoute: typeof AppArtigosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMascoteRoute: typeof AppMascoteRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArtigosRoute: AppArtigosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMascoteRoute: AppMascoteRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ConfigRoute: ConfigRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PagamentoRoute: PagamentoRoute,
  PlanosRoute: PlanosRoute,
  ArtigoIdRoute: ArtigoIdRoute,
  EdicaoIdRoute: EdicaoIdRoute,
  LerIdRoute: LerIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
